### ISSUE TITLE
Handle UnicodeDecodeError in serial_monitor.py

### ISSUE THREAD

**Issue by dbeecham** [plusterm/plusterm#3]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 608, in callit
    func(*args)
  File "/home/dbe/sources/plusterm/sm_gui.py", line 211, in listenComThread
    self.context.getdata()
  File "serial_monitor.py", line 110, in getdata
    self.logoutputtogui(result[1].decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 0: invalid
continuation byte
```

**Comment by imanhabib** [comment]
btw. did you notice that the latest revision is in the branch: unloadmodule ?

**Comment by dbeecham** [comment]
Right, yes, I should've specified that this issue is on the unloadmodule branch (though I guess it's also present in master).

**Comment by nagdil** [comment]
I did a quick fix, and this should now replace on errors (though it needs to be tested). I'll keep the issue open until it's verified to be working.

On another note, the unloadmodule is now merged into master, so feel free to use the default branch.
